### ISSUE TITLE
getImageUrl is throwing 403

### ISSUE THREAD

**Issue by Shompi** [H2Owater425/node-hitomi#35]
Any chance of getting this fixed again or is not worth the time? :(

**Comment by H2Owater425** [comment]
I'm on my way to fix it, since putting Hitomi's code directly to this package will make it heavier, I made compact way to solve this problem. 
Because of my school's graudation, I have no time now, but I think I can release a new release of this package today(in KST).
Sorry, wait for some time please.

**Comment by Shompi** [comment]
All good, take your time and good luck on your graduation!

**Comment by H2Owater425** [comment]
Thank you for words of blessing :)
Also, I got good news for you. I've just tested new code and it worked completely fine!
Below is the test result, and please check the new version when it comes out!
![image](https://user-images.githubusercontent.com/50160366/148413485-2f8325ed-a842-4764-ac09-85f6d50b80eb.png)

**Comment by Shompi** [comment]
Ok so, I got the latest version of the package (5.0.4) through npm.
I dont know if im doing something wrong or if theres something wrong with hitomi but what im doing right now is the following:

Im getting a Hitomi.Gallery with this by providing an Id
```js
const result = await Hitomi.getGallery(hitomiId, { includeFullData: true, includeFiles: true }).catch(console.log);
```
then to get the images im passing one of `result.files` objects to `getImageUrl()` like this, and logging it to the console
```js
const imageUrl = Hitomi.getImageUrl(result.files[1], result.files[1].extension);
```
I do get a url's back (this is from some other tests but using the latest version too)
![image](https://user-images.githubusercontent.com/10200647/148504349-df69c559-b9d2-4b9c-9e50-73af9161ab26.png)
and when I open them in the browser i just get 403 forbidden errors.

I think it works sometimes because im pretty sure I was able to visualize one of the images but after that it just started throwing 403s again.

If you have any idea of whats happening i would be really glad to hear it
Also I dont think I quite get what you mean setting the referer header to 'hitomi.la' since I dont see any method on your library to do that.

**Comment by H2Owater425** [comment]
Every http(s) requests have key-value data called header (I guess you will know this, but anyway)

So basically, Hitomi provides its image resources to its own services only, and they judge the origin of the request with a value of key 'Referer' in the header which is automatically filled when you use the browser.

Since your browser fills that data with its own, you need a third-party extension for you to modify the header to see them properly with your browser.
Or you can just use requesting program like Postman.

In fact, the purpose of providing the image url is to download, not see them directly from the browser. (Because it requires a lot of things)
But I hope your problem will be solved, thanks for using my package!

**Comment by Shompi** [comment]
Oh I understand now thanks you so much for explaining it to me!
I guess ill download the images and see what can I do then.

Thanks you for this library! you can close this issue.
