### ISSUE TITLE
HitomiError [INVALID_VALUE]: extension must be valid

### ISSUE THREAD

**Issue by dnm13** [H2Owater425/node-hitomi#63]
## Description of bug 
An error occurs randomly when I try to get image URIs of this gallery: 3165326
It also occurs on other gallery, and I had no reason to single out this gallery.
Though I had no idea what's the clear cause that would trigger this bug.
Code:
```typescript
import hitomi from 'node-hitomi';

(async () => {
    const getImageUrl = async function getImageUrl(image: hitomi.Image, extension: "avif" | "webp", options: { isThumbnail?: boolean | undefined; isSmall?: boolean | undefined; }) {
        await hitomi.ImageUriResolver
            .synchronize()
            .catch(err => {
                return Promise.reject(err)
            });
            
        return await hitomi.ImageUriResolver.getImageUri(image, extension, options);
    }

    hitomi.getGallery(3165326)
        .then(g => {
            g.files.forEach(v => {
                getImageUrl(v, "webp", {})
                    .then(u => console.log(u))
            })
        })
        .catch(e => console.log(e))
})();
```

Output:
```
HitomiError [INVALID_VALUE]: extension must be valid
    at w.getImageUri (D:\Projects\Sandbox\node_modules\node-hitomi\library\index.js:1:4749)
    at getImageUrl (D:\Projects\Sandbox\main.js:13:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Note that the error would happen inconsistenly.
About 2 out of 5 tries results in this error, and it doesn't persistently happen on one same image.

## Expected behavior 
No error happen and it would return the image URI as intended

## Screenshots
![image](https://github.com/user-attachments/assets/c7f6abb9-b216-49b0-b33f-25c9e94135da)

## Environment
- OS: Windows 10
- Version
  - NodeJS: 20.10.0
  - Package: 8.0.6

**Comment by H2Owater425** [comment]
<img width="1550" alt="image" src="https://github.com/user-attachments/assets/b2caec68-a6a4-4626-8380-727fe5dae795" />
<img width="1550" alt="image" src="https://github.com/user-attachments/assets/47d25232-0445-4055-b851-368c870255ea" />
<img width="1550" alt="image" src="https://github.com/user-attachments/assets/aef170bb-6c6a-4d05-8a4e-24e387eeee46" />

Even after several dozen attempts across different operating systems using the provided code, I was unable to reproduce the issue. I believe additional context about your environment will be necessary for further investigation.

**Comment by dnm13** [comment]
Could you tell me what could cause this error?

**Comment by H2Owater425** [comment]
According to the verification logic, the extension error might occur either because an invalid extension was used, or because the image lacks the corresponding has<Extension> property (e.g., hasWebp).
Since I suspect it's the latter in your case, to troubleshoot, it would be helpful to check the Gallery.files array to ensure that all images can generate a webp uri.

**Comment by dnm13** [comment]
That's the weird part
The error is inconsistent, which means there is time when the error didn't occur.
The tested gallery is only one, and it's confirmed all images can generate webp uri.
Although the error can also occur in other gallery.
Is it possible the error origins from `getGallery()` method?
It could be that it returns an incomplete result at `Gallery.files`, since that's the values used for `ImageUriResolver.getImageUri()`

**Comment by H2Owater425** [comment]
After checking several raw gallery responses, I discovered the cause of this strange behavior.

While I'm not certain exactly when it happened, it seems that after [hitomi dropped support for legacy image extensions](#46), they modified their code to bypass the validation logic when retrieving webp images.
Additionally, I believe the issue was further compounded by a problem in the switch-case logic, leading to unpredictable errors.

So I have published [a new version of the package](https://www.npmjs.com/package/node-hitomi/v/8.0.7) that fixes this problem, and if the error persists, please let me know!

**Comment by dnm13** [comment]
After several tests, it seems like the fix indeed solved this error.
I'll close it with this, thank you for your hard work!

![image](https://github.com/user-attachments/assets/f89e589d-d55a-4e3f-b902-d0ffda54f74b)
![Annotation 2024-12-22 070018](https://github.com/user-attachments/assets/f7c61da7-3a1e-4cb2-9944-df8fe7dc8e64)
